### ISSUE TITLE
NPC movement is not doing what it is suppose to

### ISSUE THREAD

**Issue by TerrorTreve** [quxios/QMV-Master-Demo#13]
NPC + autonomous movement frequency on highest = Not working

**Comment by quxios** [comment]
Will look into it, if possible please let me know how it's not working. Is it just not working at all? Because my events do move

**Comment by TerrorTreve** [comment]
Well Im not sure if i have to activate other plugins or not but if i set the npc autonomous movement to highest frequency it will not move instead will spin on the same spot moving little by little.

**Comment by quxios** [comment]
I'm assuming you mean on random movement then. Because event frequency and event movement both work as intended. Though random is no longer waiting for X steps before randomizing move direction
