### ISSUE TITLE
Incompatiblity with Region plugins of Yanfly

### ISSUE THREAD

**Issue by chaos17** [quxios/QMV-Master-Demo#2]
Hello,

Here's the list you asked on the forum to give you.
http://yanfly.moe/2015/12/27/yep-52-region-battlebacks/
http://yanfly.moe/2015/10/19/yep-17-region-events/ (I tested this)
http://yanfly.moe/2015/10/20/yep-18-region-restrictions/ (I tested this)
http://yanfly.moe/2016/10/22/yep-118-vehicle-restrictions-rpg-maker-mv/
http://yanfly.moe/2016/01/24/yep-062-slippery-tiles/ (I tested this)
http://yanfly.moe/2016/03/05/yep-79-event-chase-stealth/
http://yanfly.moe/2017/05/26/yep-138-footstep-sounds-rpg-maker-mv/

Also when I tested regions without any other plugins (so only in your demo) the game has difficulty to reconize that I'm walking on a reguin who should poison me. Example: https://cdn.discordapp.com/attachments/228916450499231744/317929176524914688/Regiondrunkgohome.gif

**Comment by quxios** [comment]
Thanks!

As for that last example, how was that done? I wasn't aware you could poison the hero with regions

**Comment by chaos17** [comment]
There is 2 way to poison someone with the region with and without using Yanfly. Unfortunately, both way react the same as in the gif. Normally when it works correctly, you see a flash every time you walk on poisoned tile but it isn't happening when using your Qmouvement.

The first way, without Yanfly: https://cdn.discordapp.com/attachments/228916450499231744/318286215113736202/unknown.png

The second way, with Yanfly (the whole video is about how you setup region to poison): https://youtu.be/qA5u5weTbxg

**Comment by quxios** [comment]
[QMovement 1.3.6](https://github.com/quxios/QMV-Master-Demo/blob/master/js/plugins/QMovement.js)
Should fix some of those plugins. The plugins that deal with any collision checking will need a patch to be made.

**Comment by quxios** [comment]
Try this js for patches for:
- YEP_RegionRestrictions
- YEP_SlipperyTiles
https://gist.github.com/quxios/110ee07a495c9a252b377d0d566d0951

Place it somewhere below QMovement and the yanfly plugins

**Comment by chaos17** [comment]
Fix work great. Region hit box is correct and region restriction work. Slippery tiles on the other hand still allow to change direction and increase the speed up a rank if a direction is pressed, ex: https://cdn.discordapp.com/attachments/228916450499231744/319458590240931840/Slip.gif

**Comment by quxios** [comment]
Ah yeah I tested it and I see now. This patch update should fix that:
https://gist.github.com/quxios/110ee07a495c9a252b377d0d566d0951

**Comment by chaos17** [comment]
Almost perfect, just the diagonal movement which seems to allow to move in a direction we're not supposed to, ex: https://cdn.discordapp.com/attachments/228916450499231744/320166605562839040/Diag.gif

**Comment by quxios** [comment]
Sorry a bit late, try this patch:
https://gist.github.com/quxios/110ee07a495c9a252b377d0d566d0951
