### ISSUE TITLE
QMovement - Change collider by using plugin command

### ISSUE THREAD

**Issue by AUXturnA** [quxios/QMV-Master-Demo#3]
Hello, quxios
May you make plugin command that can change event's/player's collider in-game?
Like your previous plugin , Quasi Movement.
For example,
`quasi collider [id] [type] [width] [height] [ox] [oy]`
(Directly copy from Quasi Movement script call, [ ] is argument.)
To change event id's(if `0`, player's) collider to (type, width, height, ox, oy).

And, additionally if you can,when  id argument is  `-1` (or something),
that means "this event".

**Comment by quxios** [comment]
Yeah I've been wanting to get to this. Will add it in when I have some free time.

The format would be:

`QMovement changeCollider [CHARAID] [TYPE] [WIDTH] [HEIGHT] [OX] [OY]`

or for using a preset
`QMovement changeCollider [CHARAID] preset [PRESET ID]`

**Comment by AUXturnA** [comment]
Hello, quxios
Thanks for response and glad to hear about that.

**Comment by quxios** [comment]
Completed, this is included in QMovement 1.4.2
https://github.com/quxios/QMV-Master-Demo/blob/master/js/plugins/QMovement.js
