### ISSUE TITLE
makeVideoPlayableInline is not defined

### ISSUE THREAD

**Issue by ZcheK** [quxios/QMV-Master-Demo#4]
Getting this error loading master demo on RMV 1.5.0, also console won't open and QUpdate is saying updates are available.

**Comment by quxios** [comment]
Don't copy the index.html file from this demo folder, not sure why I included it. I deleted it now, so shouldn't have that issue in future MV updates.

As for the QUpdate, well I'm guessing you had used an old downloaded master demo, and some of the plugins are out of date in that. Plugin updates are typically out every 1~5 days. Or do you mean it's saying there's updates but everything is up to date?

**Comment by ZcheK** [comment]
Oh the index file I should have guessed that. Working now. The update thing was because you released updates a few minutes after I downloaded the demo.
